# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(322, 352)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.checkBox_10 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_10.setGeometry(QtCore.QRect(110, 120, 92, 23))
        self.checkBox_10.setObjectName("checkBox_10")
        self.checkBox_4 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_4.setGeometry(QtCore.QRect(20, 90, 92, 23))
        self.checkBox_4.setObjectName("checkBox_4")
        self.checkBox_7 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_7.setGeometry(QtCore.QRect(110, 60, 71, 21))
        self.checkBox_7.setObjectName("checkBox_7")
        self.checkBox_9 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_9.setGeometry(QtCore.QRect(110, 90, 92, 23))
        self.checkBox_9.setObjectName("checkBox_9")
        self.checkBox_13 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_13.setGeometry(QtCore.QRect(210, 0, 61, 31))
        self.checkBox_13.setObjectName("checkBox_13")
        self.checkBox_3 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_3.setGeometry(QtCore.QRect(20, 60, 71, 21))
        self.checkBox_3.setObjectName("checkBox_3")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(210, 180, 89, 25))
        self.pushButton.setObjectName("pushButton")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(20, 0, 51, 31))
        self.checkBox.setObjectName("checkBox")
        self.checkBox_11 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_11.setGeometry(QtCore.QRect(210, 30, 61, 31))
        self.checkBox_11.setObjectName("checkBox_11")
        self.checkBox_8 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_8.setGeometry(QtCore.QRect(110, 0, 71, 31))
        self.checkBox_8.setObjectName("checkBox_8")
        self.checkBox_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_2.setGeometry(QtCore.QRect(20, 30, 61, 21))
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_6 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_6.setGeometry(QtCore.QRect(110, 30, 71, 31))
        self.checkBox_6.setObjectName("checkBox_6")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(20, 200, 91, 21))
        self.lineEdit_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(20, 160, 91, 21))
        self.lineEdit.setMaximumSize(QtCore.QSize(309, 16777215))
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.checkBox_5 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_5.setGeometry(QtCore.QRect(20, 120, 92, 23))
        self.checkBox_5.setObjectName("checkBox_5")
        self.checkBox_12 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_12.setGeometry(QtCore.QRect(210, 60, 101, 21))
        self.checkBox_12.setObjectName("checkBox_12")
        self.checkBox_14 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_14.setGeometry(QtCore.QRect(210, 90, 101, 21))
        self.checkBox_14.setObjectName("checkBox_14")
        self.checkBox_15 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_15.setGeometry(QtCore.QRect(210, 120, 92, 23))
        self.checkBox_15.setObjectName("checkBox_15")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(20, 230, 281, 111))
        self.textBrowser.setObjectName("textBrowser")
        self.verticalScrollBar = QtWidgets.QScrollBar(self.centralwidget)
        self.verticalScrollBar.setGeometry(QtCore.QRect(280, 230, 20, 111))
        self.verticalScrollBar.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar.setObjectName("verticalScrollBar")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.checkBox_10.setText(_translate("MainWindow", "Lb"))
        self.checkBox_4.setText(_translate("MainWindow", "С - 44"))
        self.checkBox_7.setText(_translate("MainWindow", "М - 2"))
        self.checkBox_9.setText(_translate("MainWindow", "WS"))
        self.checkBox_13.setText(_translate("MainWindow", "H - 60"))
        self.checkBox_3.setText(_translate("MainWindow", "С - 21"))
        self.pushButton.setText(_translate("MainWindow", "Calculate"))
        self.checkBox.setText(_translate("MainWindow", "С - 8"))
        self.checkBox_11.setText(_translate("MainWindow", "H - 75"))
        self.checkBox_8.setText(_translate("MainWindow", "МП - 18"))
        self.checkBox_2.setText(_translate("MainWindow", "С - 10"))
        self.checkBox_6.setText(_translate("MainWindow", "МП - 20"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "Width"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Height"))
        self.checkBox_5.setText(_translate("MainWindow", "КД"))
        self.checkBox_12.setText(_translate("MainWindow", "H-114 (600)"))
        self.checkBox_14.setText(_translate("MainWindow", "H-114 (750)"))
        self.checkBox_15.setText(_translate("MainWindow", "HC -35"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
